version: 2.1
orbs:
  ruby: circleci/ruby@1.7.1

jobs:
  build:
    docker:
      - image: cimg/ruby:2.6.5-node
    environment:
      BUNDLE_PATH: ~/vendor/bundle

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: a merge PR
          command: |
            if [[ -n "${CIRCLE_PR_NUMBER}" ]]; then
              git fetch origin +refs/pull/$CIRCLE_PR_NUMBER/merge:pr/$CIRCLE_PR_NUMBER/merge
              git checkout -qf pr/$CIRCLE_PR_NUMBER/merge
            fi
      - run:
          name: fetch submodules
          command: git submodule init && git submodule update

      # Download and cache dependencies
      - restore_cache:
          keys:
          - rubygems-v1-latest

      - run:
          name: install dependencies
          command: cd docs/ && bundle check || bundle install --jobs=4 --retry=3

      - run:
          name: Jekyll build
          command: cd docs/ && bundle exec jekyll build -d html 2> std.err

      - run:
          name: Check Jekyll build
          command: |
            cd docs/ && cat std.err
            exit $(wc -l std.err | awk '{print $1}')
      - run:
          name: HTMLProofer tests
          command: |
            cd docs
            bundle exec htmlproofer ./html \
              --allow-hash-href \
              --disable-external
      - run:
          name: HTMLProofer with external
          command: |
            if [ "${CIRCLE_BRANCH}" = "master" ]; then
             cd docs
             bundle exec htmlproofer ./html \
               --allow-hash-href \
               --http-status-ignore 302
               # Ignore old ideas pages and ssl certificates that error.
            fi
      - run:
          name: Jekyll re-build for local
          command: |
            cd docs/
            echo "url: https://output.circle-artifacts.com" > circle.yml
            bundle exec jekyll build -d html -b "/output/job/${CIRCLE_WORKFLOW_JOB_ID}/artifacts/0/html"  --config _config.yml,circle.yml 
            find ./html/ -type f -iname '*html' | xargs -I{} sed -i \
              -e 's|href="\(\.\/.*\/\)"|href="\1index.html"|g' \
              -e '/0\/html/ s|href="\(\/.*\/\)"|href="\1index.html"|g' {}
            # Replace pages ending on `/` from our site to direct to index.html
      - run:
          name: "Built documentation is available at:"
          command: DOCS_URL="https://output.circle-artifacts.com/output/job/${CIRCLE_WORKFLOW_JOB_ID}/artifacts/0/html/index.html"; echo $DOCS_URL

      - save_cache:
          paths:
            - ~/vendor/bundle
          key: rubygems-v1-latest

      # collect reports
      - store_artifacts:
          path: ~/repo/docs/html
          destination: html

notify:
  webhooks:
    - url: https://giles.cadair.dev/circleci