# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: AAIC 2022 Workshop Getting Started With Neuroimaging Analysis 
email:  HealthBioscienceIdeas@ucl.ac.uk 
description: >- # this means to ignore newlines until "baseurl:"
  This hands-on workshop can serve as a beginners or refresher course for established investigators, clinicians, and trainees involved in the use of imaging techniques in the study of Alzheimer’s disease, related disorders and normal aging.
twitter_username: HealthBioIdeas
github_username:  HealthBioscienceIDEAS

logo: "/assets/logo.svg"
search_enabled: true

# aux_links_new_tab: true
# aux_links:
#  "IDEAS/MedICSS Project on GitHub":
#    - "https://github.com/HealthBioscienceIDEAS/TeamCoders_Event_Based_Models"
#  "Health and Bioscience IDEAS Homepage":
#    - "https://healthbioscienceideas.github.io/" 

# Build settings
remote_theme: just-the-docs/just-the-docs

gh_edit_link: true # show or hide edit this page link

gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/HealthBioscienceIDEAS/aic2022-workshop" # the github URL for your repo
gh_edit_branch: "gh-pages" # the branch that your docs is served from
gh_edit_source: docs # the source that your files originate from

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/